### ISSUE TITLE
An intro error occurred if  system locale is  lang= ja-jp.utf-8

### ISSUE THREAD

**Issue by TomohikoSUZUKI** [jcryptool/core#236] opened 2021-02-16 06:45 UTC
Screenshot:
![VirtualBox_kali ja-jp_16_02_2021_15_00_28](https://user-images.githubusercontent.com/79124398/108027243-3487e700-706d-11eb-8d3e-5717ba642537.png)
logs
[errorlog.log](https://github.com/jcryptool/core/files/5986612/errorlog.log)
And set locale lang=en_us.utf-8. Then any error didn't occur.

I also saw same error occurred at Windows.

**Comment by simlei** [comment] 2021-02-16 17:49
Thanks for the report; the extra info about locale and the log files are appreciated! :)
I've been able to reproduce that by launching JCT via `./JCrypTool -nl jp`.
We'll be looking into the issue.

**Comment by simlei** [comment] 2021-03-09 12:38
Working on a solution for unknown locales like `jp` which JCrypTool (rather, in extension, the Eclipse RCP's localization mechanism) can't handle; something along the lines of the following screenshot:
![image](https://user-images.githubusercontent.com/982379/110470731-81466700-80db-11eb-8a0e-41275a64b61f.png)

What is currently complicating the issue is, _the restart mechanism of the Eclipse RCP is flawed_ (regular restart not possible at that early stage of the application) and there's also [this bug](https://bugs.eclipse.org/bugs/show_bug.cgi?id=323565) that makes our current approach to language changes under Linux fail. Too hasty an approach (e.g. home-made restart) _will_ introduce bugs that will make debugging this in the Eclipse IDE impossible, so we'll have to find a smarter way...

**Comment by simlei** [comment] 2021-03-16 13:58
fixed with #238; if unexpected errors occur with this, comment here & reopen.
Fix included in releases newer than and including https://github.com/jcryptool/core/releases/tag/1.0.3.01.236

**Closed as completed by simlei** 2021-03-16 13:58 UTC
