### ISSUE TITLE
Algorithms view: Authentication codes - HMac and TwoTrackMac not working

### ISSUE THREAD

**Issue by dschadow** [jcryptool/core#2] opened 2011-09-01 08:44 UTC
All entries in the Authentication codes - HMac and TwoTrackMac group are not working. A double click does not open a wizard nor does it add an entry in the Operations view. There seems to be a problem with the current version of the algorithms.xml.

**Comment by simlei** [comment] 2017-10-11 15:30
Could not reproduce, likely that the algorithms.xml problem is fixed by now. The only HMac implementation (HMacMD5) works as far as I can tell.

**Closed by simlei** 2017-10-11 15:30 UTC
Labels: Bug, FlexiProvider
