### ISSUE TITLE
macOS: The JVM shared library does not contain the JNI_CreateJavaVM symbol

### ISSUE THREAD

**Issue by dschadow** [jcryptool/core#252] opened 2021-09-19 08:04 UTC
From the JCrypTool contact form by Michael:

Startup fails with the following error message: "The JVM shared library "/Library/Java/JavaVirtualMachines/temurin-11.jre/Contents/Home/bin/../lib/server/libjvm.dylib" does not contain the JNI_CreateJavaVM symbol"

Installed Java runtime is the one from the JCT homepage.

java --version
openjdk 11.0.12 2021-07-20
OpenJDK Runtime Environment Temurin-11.0.12+7 (build 11.0.12+7)
OpenJDK 64-Bit Server VM Temurin-11.0.12+7 (build 11.0.12+7, mixed mode)

macOS 10.15.7

**Comment by dschadow** [comment] 2021-09-19 14:38
I am able to reproduce the error on macOS 11.6 with only the the linked Java version installed. JCT did not work with the Temurin 11 JDK either (in fact none of the Temurin versions did, in my eyes we should recommend installing another Java version (SDK), even if that ends up in a larger download).

**Comment by StanciuMarian** [comment] 2021-10-03 10:51
@dschadow did you find a workaround or a JRE/JDK that actually works? I encounter the same problem on a M1 macbook

**Comment by simlei** [comment] 2021-10-04 10:11
Could either of you try it with other JREs? I would suggest using https://sdkman.io/ for managing the active JRE, or a similar SDK manager. When installed, sdkman command `sdk list java` should give you candidates like...
```
Available Java Versions
================================================================================
 Vendor        | Use | Version      | Dist    | Status     | Identifier
--------------------------------------------------------------------------------
 AdoptOpenJDK  |     | 16.0.1.j9    | adpt    |            | 16.0.1.j9-adpt      
               |     | 16.0.1.hs    | adpt    |            | 16.0.1.hs-adpt      
               |     | 11.0.11.j9   | adpt    |            | 11.0.11.j9-adpt     
               | >>> | 11.0.11.hs   | adpt    | installed  | 11.0.11.hs-adpt     
               |     | 8.0.292.j9   | adpt    |            | 8.0.292.j9-adpt    
```

and many other venders, like temurin.
Please do try `11.0.11.hs` first if you use sdkman.

Thanks already!

**Comment by simlei** [comment] 2021-10-27 09:08
Turns out, the JRE may have been the culprit after all!
With Amazon Corretto, these problems did disappear in one test for us. It would be nice if you could affirm that.

- Download and install this JRE: https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/downloads-list.html
- Follow the other OSX-Instructions [on the download page](https://www.cryptool.org/en/jct/downloads), most importantly, the `sudo xattr -r -d [...]`

Thanks! :)

**Comment by StanciuMarian** [comment] 2021-11-01 12:32
I can confirm that it is working with Amazon Corretto 11 on a M1 Macbook.

Thanks for the help

**Comment by simlei** [comment] 2021-11-01 12:48
Great, thanks for confirming! I am closing this issue — further work on OS/X compatibility is planned, i.e. we want to be able to package the JRE with the product so that no JRE installation at all is required.

**Closed as completed by simlei** 2021-11-01 12:48 UTC

**Comment by kheitkamp** [comment] 2023-09-27 10:02
Still works, on an M1 with the Amazon Corretto using Ventura 13.5.2

**Comment by simlei** [comment] 2023-09-27 15:48
Great news, thanks for reporting!
