### ISSUE TITLE
Crypto explorer: disable opening context help

### ISSUE THREAD

**Issue by simlei** [jcryptool/core#195] opened 2020-04-23 16:19 UTC
Make it so that the crypto explorer view does not automatically open the context help window on selection of an entry, if the context help is currently hidden. To the effect of not losing focus of the view shortly.

**Comment by grthor** [comment] 2020-07-08 14:34
I just took a look into this problem. The code was easy to find because some invested 30 seconds to write a small comment in the code on what is happening. Thanks for that.

https://github.com/jcryptool/core/blob/ba8cb0c7500066c31ba3d67ea8b16d6821ded8ff/org.jcryptool.crypto.flexiprovider.algorithms/src/org/jcryptool/crypto/flexiprovider/algorithms/ui/views/FlexiProviderAlgorithmsView.java#L149-L172

I could simply delete this part of code, but before I would like to discuss the problem. 
The problem was that the algorithm explorer loses focus (and the context helpgets it) after you select an entry in the algorithm explorer, right? I could not reproduce it. For me it works fine, see the gif.

![entrySelection](https://user-images.githubusercontent.com/20046726/86931778-cbd0a780-c138-11ea-8224-f94ad3df4466.gif)

As you can see, the algorithm explorer does not lose focus.

**Can somebody reproduce / explain the problem in more detail?**

**Comment by grthor** [comment] 2020-07-08 14:36
Here is a possibility to force focus on the algorithm view after openening the contect help.

```
IWorkbenchPart t = getSite().getPart();
PlatformUI.getWorkbench().getActiveWorkbenchWindow().getActivePage().activate(t);
```

**Comment by simlei** [comment] 2020-07-09 10:31
Hi, 

I'm pretty sure the problem was that opening the context view stole the focus briefly (giving it back thereafter).
I think this is still the case. The focus was returned already when this issue was openend, as is the case now.

However, previously, this caused double clicks on an item in the explorer to not get recognized, if the context view was not openend at the time of the double click. This is not the case anymore on my PC. May be this is due to updating to a newer version of the eclipse platform. Anyhow, without the double click issue, I think this can be closed. Thanks for looking into it :)

**Comment by grthor** [comment] 2020-07-09 13:42
As this problem could not be reproduced on three machines (2x Windows, 1x Linux) i assume the problem was fixed by an Eclipse update. Therefore I close this issue.

**Closed as completed by grthor** 2020-07-09 13:42 UTC
