### ISSUE TITLE
Any crypto operation failing on MacOS Catalina

### ISSUE THREAD

**Issue by dschadow** [jcryptool/core#178] opened 2020-03-15 07:53 UTC
Applying any crypto operation (encrypt, sign, hash) on MacOS Catalina with Java 13 (others might be affected too) fails at least in latest weekly build. This happens when using an open file in any of the editors or via context menu in file explorer:

!ENTRY org.jcryptool.crypto.flexiprovider.engines 4 0 2020-03-15 08:49:09.789
!MESSAGE Must specify a URI scheme:%3CActive%20Editor%3E
!STACK 1
org.eclipse.core.runtime.CoreException: Must specify a URI scheme:%3CActive%20Editor%3E
	at org.eclipse.core.internal.filesystem.Policy.error(Policy.java:48)
	at org.eclipse.core.internal.filesystem.Policy.error(Policy.java:43)
	at org.eclipse.core.internal.filesystem.InternalFileSystemCore.getStore(InternalFileSystemCore.java:109)
	at org.eclipse.core.filesystem.EFS.getStore(EFS.java:479)
	at org.jcryptool.crypto.flexiprovider.engines.FlexiProviderEngine.getFileInputStream(FlexiProviderEngine.java:132)
	at org.jcryptool.crypto.flexiprovider.engines.FlexiProviderEngine.initInput(FlexiProviderEngine.java:102)
	at org.jcryptool.crypto.flexiprovider.engines.cipher.CipherEngine.perform(CipherEngine.java:110)
	at org.jcryptool.crypto.flexiprovider.engines.listener.PerformOperationListener.performOperation(PerformOperationListener.java:33)
	at org.jcryptool.crypto.flexiprovider.operations.engines.PerformOperationManager.firePerformOperation(PerformOperationManager.java:44)
	at org.jcryptool.crypto.flexiprovider.integrator.IntegratorHandler.execute(IntegratorHandler.java:338)
	at org.jcryptool.core.operations.algorithm.ShadowAlgorithmHandler.execute(ShadowAlgorithmHandler.java:117)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:498)
	at org.jcryptool.fileexplorer.popup.contributions.CryptoContributionItem.run(CryptoContributionItem.java:142)
	at org.jcryptool.fileexplorer.popup.contributions.CryptoContributionItem$2.widgetSelected(CryptoContributionItem.java:104)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4406)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4193)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3810)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:633)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.jcryptool.core.Application.start(Application.java:45)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)

**Comment by dschadow** [comment] 2020-03-15 16:35
Happens on Windows 10 and Java 8 too.

**Comment by grthor** [comment] 2020-03-15 19:02
I tried the past WBs until the WB of 31.08.19. It never worked.

**Comment by grthor** [comment] 2020-03-15 19:10
I have tested a little further until 23.02.2019. It does not work. But since I assume that it has worked in the meantime I think it is due to a Java Update. This is the only thing that remained the same during my tests. Unfortunately I don't have an older Java version than 8u221 so I can't test with an older version.

**Comment by grthor** [comment] 2020-03-15 19:55
After some debugging I found a point in [FlexiProviderEngine.java](https://github.com/jcryptool/core/blob/develop/org.jcryptool.crypto.flexiprovider.engines/src/org/jcryptool/crypto/flexiprovider/engines/FlexiProviderEngine.java) that doesn't seem right to me and if you change it the algorithms work again. But the strange thing is that nothing has been changed on this one for 6 years.

Line 93 checks whether the active editor should be used as input. This is done by comparing `input` with `Messages.InputType`. `input` was always `<Active Editor>` during debugging. But because he compared input with the german translation of `Messages.InputType` (`Aktiver Editor`) this was never the case and so he jumped into the else-part of the statement where the exception is thrown a bit later instead of staying in the if-part that seems to load the editor content correct.

https://github.com/jcryptool/core/blob/799f63de72d9e934f641169ec03a714c1b603e24/org.jcryptool.crypto.flexiprovider.engines/src/org/jcryptool/crypto/flexiprovider/engines/FlexiProviderEngine.java#L91-L105

https://github.com/jcryptool/core/blob/799f63de72d9e934f641169ec03a714c1b603e24/org.jcryptool.crypto.flexiprovider.engines/src/org/jcryptool/crypto/flexiprovider/engines/messages.properties#L5
https://github.com/jcryptool/core/blob/799f63de72d9e934f641169ec03a714c1b603e24/org.jcryptool.crypto.flexiprovider.engines/src/org/jcryptool/crypto/flexiprovider/engines/messages_de.properties#L5

I would check in line 93 instead of against Messages.inputType against an untranslated string <Active Editor> whether to use the current editor as input or not.

https://github.com/grthor/core/blob/8549e93ca33b4146fb90fab60b909ebb4698e9aa/org.jcryptool.crypto.flexiprovider.engines/src/org/jcryptool/crypto/flexiprovider/engines/FlexiProviderEngine.java#L91-L105

What do you think of this?

**Comment by grthor** [comment] 2020-03-17 12:24
I have dealt again with the problem, because I thought that it must work with the english JCT, because there is input = \<Active Editor\>. It works in the english version. 
But after changing the language it also works in German. 
My new assumption is that the initial setting of the language does not work properly. All texts in the JCT are in German on first start (no .jcryptool folder). In the settings, however, English is shown as the set language.

**Comment by simlei** [comment] 2020-03-17 13:33
> My new assumption is that the initial setting of the language does not work properly. All texts in the JCT are in German on first start (no .jcryptool folder). In the settings, however, English is shown as the set language.

May be the initially-chosen language is the system locale (i.e. what the OS is configured for)? And we just do not display it properly?

**Comment by simlei** [comment] 2020-03-17 13:36
> What do you think of this?

If your solution works -- 

> I would check in line 93 instead of against Messages.inputType against an untranslated string whether to use the current editor as input or not.

-- then I say it is the way to go. Does it work after building it with Maven on Windows? I'd be happy to test a product on Ubuntu and OSX if you post a link!

**Comment by grthor** [comment] 2020-03-17 16:31
Still puzzled by the wrong language in the settings, I dug a little deeper and found the cause of the problem. (At least thats what I think at the moment 😄)

I noticed that the algorithms worked for both languages after changing the language in the preferences. If there is no language specified and the JCT uses the OS language the problem occurs. After setting a language the problem does not occur anymore.

The following code snippet should check if the OS language is german or englisch and elsewhere set it to english. It works fine if the language is specified with `-nl en` or `-nl de`. But if no language is specified via `-nl` JCT uses the OSs language and then `Locale.getDefault()` and `Locale.GERMAN` are not equal, even if the OSs language is german.

https://github.com/jcryptool/core/blob/799f63de72d9e934f641169ec03a714c1b603e24/org.jcryptool.core/src/org/jcryptool/core/Application.java#L32-L41

I am going to build a product with my fix and post a dowload link here

**Comment by grthor** [comment] 2020-03-17 16:44
Here is a link to the files. Keep in mind that i build on windows and the file rights may not be correct.
https://1drv.ms/u/s!AhiI0xDdcEFsgahczlKsd0wk9bvWZg?e=ffzAh8

My fix also resolves the problem with the wrong language in the preferences.

**Comment by simlei** [comment] 2020-03-17 17:46
Awesome work

**Comment by grthor** [comment] 2020-03-20 17:25
I have merged the fix, so it will be included in tomorrow's WB. 

It would be good if you could test if it works.

Just delete the .jcryptool folder, start the JCT and let it calculate the MD5 hash of the example text.

If you get an output it works, if not, then apparently not.

**Comment by simlei** [comment] 2020-03-20 19:04
I am not seeing this issue on my machine, unfortunately. Thus, I cannot confirm that the change works. What I can confirm is that it continues to work on: 

- Ubuntu
- virtual OS X (vmware, Catalina)

on my machine.

I was testing with the most recent weekly build as well as a maven-built version of caac49e92440fda77289606e23b130789c6c8154 (current commit of core) as well as an up-to-date crypto repository. 
Both OS are configured with EN-US as system locale. My Ubuntu does not offer switching to german easily, on OSX I fear it would take days because it runs so slow.

**Comment by grthor** [comment] 2020-03-21 10:49
Thanks for testing.

Maybe it works on a system with English as default language. I have only tested it on system with German as default language. 

Maybe @dschadow can test todays WB if the problem still occurs. @be4 will test it this weekend.

**Comment by grthor** [comment] 2020-03-24 12:06
Since it works for @be4 and me I close the issue.

**Closed as completed by grthor** 2020-03-24 12:06 UTC
Labels: Showstopper
