### ISSUE TITLE
NSIS installer (setup.exe) requires admin rights

### ISSUE THREAD

**Issue by rofrol** [jcryptool/core#104] opened 2015-06-25 11:46 UTC
Installing KDiff3-64bit-Setup_0.9.98-2.exe on Windows 7 Enterprise. Still asks for admin password

same as closed #20

**Comment by dschadow** [comment] 2015-06-27 16:34
Confirmed. Since Eclipse NSIS is not active (any more) we will have to find another solution to provide native installers. Maybe we can use [Eclipse Oomph](https://wiki.eclipse.org/Eclipse_Installer) in the future.

**Comment by dschadow** [comment] 2016-01-16 11:40
Closing this ticket since we need a new installer and can't fix NSIS any more.

**Closed by dschadow** 2016-01-16 11:40 UTC
